from pathlib import Path

PASTA_ATUAL = Path(__file__).resolve().parent
PASTA_RAIZ_PROJETO = PASTA_ATUAL

NOME_PASTA_DATASET = "dataset"
PASTA_DATASET = PASTA_RAIZ_PROJETO / NOME_PASTA_DATASET
PASTA_TREINO = PASTA_DATASET / "train"
PASTA_VALIDACAO = PASTA_DATASET / "val"

PASTA_MODELOS_SALVOS = PASTA_RAIZ_PROJETO / "modelos_salvos"
NOME_MODELO_SVM = "classificador_svm.joblib"
NOME_ROTULOS_CLASSES = "rotulos_classes.joblib"
CAMINHO_MODELO_SVM = PASTA_MODELOS_SALVOS / NOME_MODELO_SVM
CAMINHO_ROTULOS_CLASSES = PASTA_MODELOS_SALVOS / NOME_ROTULOS_CLASSES

PASTA_MODELOS_SALVOS.mkdir(parents=True, exist_ok=True)
PASTA_IMAGENS_ORIGINAIS = PASTA_RAIZ_PROJETO / "imagens_originais"